framework:
    messenger:
        transports:
            async: 'sync://'

        routing:
            'App\Message\ProcessEmailMessage': async
            'App\Message\EmailReceivedMessage': async
